sprint_11_add-friends-like выполнено задание
deicida6/java-filmorate pull request #6
Opened 2024-05-06 12:19 UTC by deicida6

2024-05-06 12:57 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-05-06 12:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage filmStorage;
тут только FilmService filmService;

а storage вы инжектите в service-ах.
repository -> service -> controller

2024-05-06 12:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final InMemoryUserStorage userStorage;
смотрите комменты в FilmController

2024-05-06 12:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +
еще надо хендлить Internal server error

2024-05-06 12:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> usersWhoLiked;
просто likes

2024-05-06 12:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
private final FilmStorage filmStorage;
private final UserStorage userStorage;

2024-05-06 12:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final InMemoryUserStorage userStorage;
private final IUserStorage userStorage;

2024-05-06 12:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(@Autowired InMemoryFilmStorage filmStorage, @Autowired InMemoryUserStorage userStorage) {
конструктор удалить и над классом аннотацию RequiredArgsConstructor

2024-05-06 12:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(@Autowired InMemoryUserStorage userStorage) {
конструктор удалить и над классом аннотацию RequiredArgsConstructor

2024-05-06 12:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Long id : userStorage.getUser(userId).getFriends()) {
просто 
return userStorage.getUser(userId).getFriends(); --- но тут еще  userStorage.getUser(userId) надо проверить на null
   .

2024-05-06 14:54 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage filmStorage;
т.е. я правильно понял что методы которые я вызывал напрямую из storage нужно сделать обращение к ним из сервиса? я что-то запутался немного

2024-05-06 15:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage filmStorage;
да

2024-05-06 17:49 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Long id : userStorage.getUser(userId).getFriends()) {
а вот тут еще вопрос, friends это список idшников, а на выход идут юзеры, так конструкция требует все равно переливать из одного типа в другой, но я до конца не понимаю как лучше хранить в id или в user, в ТЗ написано id

2024-05-07 09:43 UTC, ErkinKasymaliev approved these changes
привет, уже лучше!
работа принята, только перед мержем поправьте коммент

2024-05-07 09:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public User getUser(Long userId) {
это должно быть в UserService

2024-05-07 09:43 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public User getUser(Long userId) {
короче удалите это и  private final UserStorage userStorage; отсюда

2024-05-07 10:17 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public User getUser(Long userId) {
а как тогда проверять пользователей в методах добавления лайк и удаления лайка без доступа к UserService и UserStorage?

2024-05-07 11:00 UTC, merged