Sprint-12-add-database выполнение задания
deicida6/java-filmorate pull request #7
Opened 2024-05-09 09:30 UTC by deicida6

2024-05-09 17:25 UTC, vinnipooha commented on src/main/resources/ER_diagram.png
Диаграммы у нас в целом одинаковые, так что мыслим в одном направлении. 
1. По структуре у меня замечание только одно  - первичный ключ **friendship_id** ни в одной из таблиц, кроме **friends** не фигурирует. Т.к. выборка статусов делается по уникальным парам user_id+user_id, то было бы удобнее их и использовать в качестве составного первичного ключа.
2. В таблице **friends** было бы для понимания понятнее, если бы идентификаторы именовались user1_id и user2_id (в этом случае сразу видно, что речь идет о двух разных пользователях, а не о двух разных id одного и того же пользователя)
3. В таблице **films**, полагаю, опечатка в типе значений поля description
4. Таблицу **genre** лучше переименовать в **genres**, т.к. она включает все их разновидности
5. Таблицу **mpa** лучше переименовать в **rating_mpa** / **ratings_mpa** , т.к. сама по себе аббревиатура mpa не совсем однозначно идентифицирует понятие
6. В таблицах **genre_films** и likes было бы удобнее сделать пары значений составными ключами
7. Ну и общим нашим недочетом будет то, что для id надо было бы использовать тип bigint, раз уж у нас в проекте id типа Long

2024-05-09 17:49 UTC, vinnipooha commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +package ru.yandex.practicum.filmorate.model;
Уверен, что перечисление будет оптимальным для списка жанров?
Эта сущность не будет соответствовать диаграмме, т.к. там у тебя связка через genre_id, а в описанном тобой случае она бы осуществлялась через name

2024-05-09 17:52 UTC, vinnipooha commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      public void addLike(Long id) {
А тут точно нужен метод по добавлению лайков? Список же можно через get вытащить и добавить все, что требуется
Фильм может относиться к нескольким жанрам (по ТЗ), так что тут тоже будет Set<(тут либо int либо Genre)> genres
private String mpa -> private Mpa mpa (это же значение из перечисления), то же касается и genre

2024-05-09 17:53 UTC, vinnipooha commented on src/main/java/ru/yandex/practicum/filmorate/model/StatusFriendship.java
> +public enum StatusFriendship {
А оно тебе надо это дополнительное перечисление? В диаграмме булево значение.

2024-05-09 17:58 UTC, vinnipooha commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>          friends.add(id);
Удобнее будет, если вместо списка Set<Long> friends возьмешь Map<Long, Boolean> friends
Ибо само по себе одиночное поле ничего не значит, т.к. оно будет относиться к конкретному объекту User, а он будет для кого-то подтвержденным другом, для кого-то неподтвержденным, а кого-то и вообще знать не знает

2024-05-09 18:00 UTC, vinnipooha reviewed
Прошлась по сущностям. По-хорошему, они в ревью не должны входить, но я до кучи просмотрела

2024-05-09 21:17 UTC, deicida6 commented on src/main/resources/ER_diagram.png
1. у таблицы должен быть уникальный ключ, зачем их два когда есть один
2. как не назови суть не меняется,
3. опечатки там нет, как выяснилось это синонимы в бд, и varchar зарезервирован за ORACLE и при запуске будут все VARCHAR заменены на VARCHAR2
4. при названии я имел ввиду сущность, а не то что это список
5. можно но так написанно в ТЗ
6. зачем, они проходные для реализации связи многие ко многим
7. только если для отражения того что мы использовали тип Long в коде

2024-05-09 21:18 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +package ru.yandex.practicum.filmorate.model;
эта часть еще никак не разрабатывался, в ТЗ этого нет

2024-05-09 21:19 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      public void addLike(Long id) {
эта часть еще никак не разрабатывался, в ТЗ этого нет

2024-05-09 21:19 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/model/StatusFriendship.java
> +public enum StatusFriendship {
пока пусть будет, удалить всегда можно

2024-05-09 21:19 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>          friends.add(id);
эта часть еще никак не разрабатывался, в ТЗ этого нет

2024-06-01 05:04 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-06-01 05:04 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        if (service.getById(id) == null) {
по хорошему эту проверку и выкидывали исключений надо убрать в сервис

2024-06-01 05:04 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +        if (service.getById(id) == null) {
по хорошему эту проверку и выкидывали исключений надо убрать в сервис

2024-06-01 05:04 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final GenreDbStorage genreStorage;
инжектим интерфейсы как FilmStorage выше

2024-06-01 05:04 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setLikes(filmStorage.getLikes(film.getId()));
а вот это неправильно. Представим что filmStorage.getAllFilms() вернет вам 1000 фильмов, и в этом цикле у вас будет 3000 вызовов в бд, а за такое обычно убивают. Что вам нужно сделать:
 filmStorage.getAllFilms(); -- в этом запросе добавьте join-ы чтобы вытащить сразу и лайки, и жанры с mpa

2024-06-01 05:04 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            user.setFriends(storage.getFriends(user.getId()));
смотрите коммент getAllFilms() в FilmService

2024-06-01 08:17 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setLikes(filmStorage.getLikes(film.getId()));
я вот не совсем понимаю, мне нужно тогда получается в объекте film массивы лайков, жанров, mpa хранить только id типа лонг? ибо в том виде в каком есть сейчас я не понимаю как одним запросом получить все разом

2024-06-01 08:31 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setLikes(filmStorage.getLikes(film.getId()));
Через join-в

2024-06-01 08:33 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setLikes(filmStorage.getLikes(film.getId()));
ну т.е. типы правильно

2024-06-01 08:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setLikes(filmStorage.getLikes(film.getId()));
Да, подтянуть mpa и жанры к фильмам одним запросом

2024-06-01 09:12 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setLikes(filmStorage.getLikes(film.getId()));
а там нужно обьединять данные через ARRAY_AGG в sql чтобы выгружать группы значений?, я не понимаю как именно массивы выгрузить

2024-06-01 10:03 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setLikes(filmStorage.getLikes(film.getId()));
вот ваш запрос FilmStorage "SELECT * FROM films"
надо так:
SELECT f.*, g.*, m* FROM films f join genre g on g.film_id = f.id join mpa m on m.film_id = f.id

2024-06-01 11:12 UTC, deicida6 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setLikes(filmStorage.getLikes(film.getId()));
загвоздка получается что результат содержит повторяющиеся значения что один фильм имеет несколько лайков и жанров, из-за чего данные выгружаются не корректно, это получается нужно в маппере уже ловить? или это по прежнему путем запроса регулируется?

2024-06-01 11:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setLikes(filmStorage.getLikes(film.getId()));
Да, сгруппируйте все в маппере

2024-06-02 12:03 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-06-02 13:50 UTC, merged